name: Build Photo Frame Controller OS Image

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 180

    steps:
      - uses: actions/checkout@v4

      - name: Install required packages
        run: |
          sudo apt update
          sudo apt install -y \
            git \
            coreutils \
            quilt \
            parted \
            qemu-user-static \
            debootstrap \
            zerofree \
            zip \
            dosfstools \
            e2fsprogs \
            libarchive-tools \
            libcap2-bin \
            rsync \
            grep \
            udev \
            xz-utils \
            curl \
            xxd \
            file \
            kmod \
            bc \
            binfmt-support \
            ca-certificates \
            fdisk \
            gpg \
            pigz \
            arch-test

      - name: Build OS image
        working-directory: image-builder
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Upload OS Image
        uses: actions/upload-artifact@v4
        with:
          name: photo-frame-controller-os-image
          path: image-builder/pi-gen/deploy/*.img
