name: Build Photo Frame Controller OS Image

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 180

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm,arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build OS image
        working-directory: image-builder
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Upload OS Image
        uses: actions/upload-artifact@v4
        with:
          name: photo-frame-controller-os-image
          path: image-builder/pi-gen/deploy/*.img
